### ISSUE TITLE
Global (Admin Site)

### ISSUE THREAD

**Issue by garg3133** [salarx/Fusion#17]
- [ ] 1. In "holds_designation" table, same person can have two same or different designations at the same time.

![talib](https://user-images.githubusercontent.com/39924567/65509111-58361480-deef-11e9-9ad7-46730fa310e1.jpg)

- [ ] 2. Unable to delete any entry from "holds_designation" table.

![talib](https://user-images.githubusercontent.com/39924567/65509297-c5e24080-deef-11e9-9cec-5c4f5a446366.jpg)

**Comment by manavgoyal53** [comment]
I have pushed some changes done in models. Make migrations and check again making entries again.
