### ISSUE TITLE
Central Mess - Mess Manager

### ISSUE THREAD

**Issue by garg3133** [salarx/Fusion#18]
- [ ] 1. The left-side menus are appearing twice in Central Mess module of "Mess Manager" in talib account.

![talib](https://user-images.githubusercontent.com/39924567/65509470-31c4a900-def0-11e9-9146-61f412d2f117.jpg)

- [ ] 2. If we add "Mess Manager" designation in "holds_designation" table twice, the left-side menus appear 3 times (in talib account, not checked by making any other account).

![talib](https://user-images.githubusercontent.com/39924567/65509658-93851300-def0-11e9-9cc2-97243fe6750c.jpg)

![talib](https://user-images.githubusercontent.com/39924567/65509739-c29b8480-def0-11e9-9ce6-4da6db5c47d2.jpg)

**Comment by manavgoyal53** [comment]
I have made the restrictions in the HoldsDesignation model of central_mess application. Now admin won't be able to create a user with already existing entry with same designation. Also the front end-part of this module seems to be working fine on my system.
![Opera Snapshot_2019-09-30_222805_localhost](https://user-images.githubusercontent.com/39936373/65899831-37c7f780-e3d2-11e9-991c-877ec2cddccc.png)
![Opera Snapshot_2019-09-30_223023_localhost](https://user-images.githubusercontent.com/39936373/65899850-40203280-e3d2-11e9-96c9-6a36dd525db5.png)
