### ISSUE TITLE
Leave Module - When date not entered

### ISSUE THREAD

**Issue by garg3133** [salarx/Fusion#2]
When dates are not entered in the Responsibility step, it does not ask for date and moves to next step but shows error after submitting in the last step.

![2019-09-08](https://user-images.githubusercontent.com/39924567/64485787-670b9e80-d242-11e9-94c4-6a7f097b406a.png)
![2019-09-08 (1)](https://user-images.githubusercontent.com/39924567/64485785-6410ae00-d242-11e9-871b-cf241e97043a.png)
![2019-09-08 (2)](https://user-images.githubusercontent.com/39924567/64485788-696df880-d242-11e9-9ba8-8ea4e4b6d4c9.png)

Either it should show some warning while submitting the second step or just copy the date from the first step.

Same problem also exists in the first step... Even if we don't enter anything in the first step, it moves to the second step and then to the third step and shows error only on submitting the whole leave application.

I also think that the steps written above should be clickable to go to the backward step but not to the next step. To go to the previous step, user will always first click on those steps and then will try to find if there is any other option to go back.

![2019-09-08 (3)](https://user-images.githubusercontent.com/39924567/64485910-d2a23b80-d243-11e9-9514-a3a82b6c8863.png)

**Comment by adi0311** [comment]
1. The dropdown list becomes annoying and opens up on hovering the mouse. It should open on click of the mouse.
![2019-09-09 (9)](https://user-images.githubusercontent.com/51120669/64507071-50734f00-d2f7-11e9-9ebe-d2443a216633.png)

2. In the leave type "Vacation", after submitting an error page is displayed.
![2019-09-09 (8)](https://user-images.githubusercontent.com/51120669/64506923-e490e680-d2f6-11e9-9b57-7ce22958bd25.png)

**Comment by garg3133** [comment]
**From Student's Account**

- [ ] 1. On selecting Casual Leave Type, this error appears.

![2019-09-10](https://user-images.githubusercontent.com/39924567/64589771-8b42b900-d3c3-11e9-9836-98bf698115a2.png)

![2019-09-10 (1)](https://user-images.githubusercontent.com/39924567/64589775-90a00380-d3c3-11e9-977a-789b1155dffa.png)

- [ ] 2. On selecting Medical Leave Type, this error appears.

![2019-09-10 (2)](https://user-images.githubusercontent.com/39924567/64589860-d65ccc00-d3c3-11e9-81db-a0c56ac36f8b.png)

![2019-09-10 (3)](https://user-images.githubusercontent.com/39924567/64589870-d9f05300-d3c3-11e9-870f-34c4b8983486.png)
