### ISSUE TITLE
central mess

### ISSUE THREAD

**Issue by VikasPandey3** [salarx/Fusion#20]
click on central mess button showing error if login by student account. 
![vst](https://user-images.githubusercontent.com/52690920/65710500-c544d800-e0b0-11e9-8a6c-50258fffd714.jpg)

**Comment by garg3133** [comment]
You'll have to add that student in the "messinfo" table under Central_Mess.

**Comment by manavgoyal53** [comment]
If you guys find any solution for an issue, please discuss it among yourselves and comment the solution for that issue. Sometimes it might happen that you have taken a temporary approach. So mention all the steps clear like after making an entry in a table the issues was solved. Also mention anything which seems doubtful to you.
