### ISSUE TITLE
Placement Module - When word instead of number entered

### ISSUE THREAD

**Issue by adi0311** [salarx/Fusion#3]
When a word is entered in the Year Text Box, no warning is shown to the user. But when the user hits search, an error page is displayed.

![2019-09-08 (1)](https://user-images.githubusercontent.com/51120669/64487576-e0fb5200-d259-11e9-9071-2e785995c8ad.png)
![2019-09-08](https://user-images.githubusercontent.com/51120669/64487575-dfca2500-d259-11e9-822c-5c4ebb56b798.png)

If a word is entered in place of an error, it should either show "DATA NOT FOUND" after hitting the search button or give a warning to the user when a word is entered instead of a number.

**Comment by salarx** [comment]
year, along with roll no, ctc fixed. 
year takes 2019 by default and should not accept any non integer characters.
roll number should only take integers
ctc will take either integers or decimal numbers, decimal numbers are increased in a step of 0.25
