### ISSUE TITLE
Visitor Hostel - Form Submission

### ISSUE THREAD

**Issue by garg3133** [salarx/Fusion#6]
1. No close button on "Place a Request" modal. We have to click outside of it to close it. 

![2019-09-08 (6)](https://user-images.githubusercontent.com/39924567/64492278-fc814f80-d28f-11e9-83f9-9c5ae0218a28.png)

2. On submitting an empty form, an alert appears with no close button. We have to click on outside of alert to close it.

![2019-09-08 (5)](https://user-images.githubusercontent.com/39924567/64492386-ef189500-d290-11e9-865c-dbf29b10da8f.png)

On leaving empty fields in the first step, it should warn about the empty necessary fields on clicking "Next" and should not go to the next step until and unless all the necessary fields are filled.

3. On closing the alert, the form should automatically reappear but we have to open it explicitly by clicking on the "Place Request" button.

4. On opening the form again after closing the alert, the "Arrival Date" do not show date picker.

![2019-09-08 (7)](https://user-images.githubusercontent.com/39924567/64492538-79adc400-d292-11e9-94d6-c1753861cd47.png)

5. Date picker of "Departure Date" is not shown properly.

![2019-09-08 (8)](https://user-images.githubusercontent.com/39924567/64492555-acf05300-d292-11e9-9c62-91b396004ecb.png)

6. Except for the "Category" dropdown, all other dropdowns once opened do not close on clicking anywhere outside but only on clicking on either the small downward arrow on the field or on any other dropdown field.

![2019-09-08 (9)](https://user-images.githubusercontent.com/39924567/64492718-a531ae00-d294-11e9-88d6-14ce922097f1.png)

Same problem with Nationality dropdown in "Visitor's Details" tab.

7.  00 option not present in "Minutes" dropdown.

![2019-09-09](https://user-images.githubusercontent.com/39924567/64492737-e1fda500-d294-11e9-9c1e-6ce5c52f48ec.png)

8. "Bill to be settled by" dropdown not opening.

9. Hours and minutes dropdowns unable to find single-digit numbers when typed without 0.

![2019-09-09 (1)](https://user-images.githubusercontent.com/39924567/64492788-b29b6800-d295-11e9-9768-fee8d28092ae.png)

10. No point 2 present in Rules and Regulations (I).

![2019-09-09 (2)](https://user-images.githubusercontent.com/39924567/64492805-132aa500-d296-11e9-860c-a4b6a25e2912.png)

**Comment by garg3133** [comment]
11. No alerts even if "Purpose of Visit" and "Bill to be settled by" fields not filled.

**Comment by adi0311** [comment]
> 1. No alerts even if "Purpose of Visit" and "Bill to be settled by" fields not filled.

1. It accepts phone number even if we enter letters in place of digits.

2. Visitor's Name and the Email field is empty in Visitor's details.

![2019-09-09 (4)](https://user-images.githubusercontent.com/51120669/64503728-02a41a00-d2ea-11e9-93e3-5cf14f539774.png)

**Comment by garg3133** [comment]
12. If we press the mouse button inside any field while selecting the content and leave the mouse button outside the modal, the modal disappears. The disappearance of the modal should be triggered in pressing mouse button and not on leaving it.

**Comment by garg3133** [comment]
> > 1. No alerts even if "Purpose of Visit" and "Bill to be settled by" fields not filled.
> 
> 1. It accepts phone number even if we enter letters in place of digits.
> 2. Visitor's Name and the Email field is empty in Visitor's details.
> 

Fine on my pc. Its alerting if Visitor's name, email field or phone number is left empty. It is also alerting if invalid phone number is entered.

![2019-09-09 (4)](https://user-images.githubusercontent.com/39924567/64504629-21a4ab00-d2ee-11e9-9d08-d054e2e6895e.png)

![2019-09-09 (5)](https://user-images.githubusercontent.com/39924567/64504657-4d279580-d2ee-11e9-92df-1364d3a7a189.png)

![2019-09-09 (7)](https://user-images.githubusercontent.com/39924567/64504664-51ec4980-d2ee-11e9-933c-8667e7fb4f39.png)

![2019-09-09 (6)](https://user-images.githubusercontent.com/39924567/64504666-557fd080-d2ee-11e9-8aad-cc6e4b0966e9.png)

**Comment by adi0311** [comment]
On cancellation,
"Cancel" button not present in Visitor's Details but only visible in Booking Details. It should be present in both places.


![2019-09-09 (5)](https://user-images.githubusercontent.com/51120669/64503935-0dab7a00-d2eb-11e9-964a-13e4d3207276.png)
![2019-09-09 (7)](https://user-images.githubusercontent.com/51120669/64503949-1b60ff80-d2eb-11e9-92b7-248924237667.png)

**Comment by garg3133** [comment]
**From VhCaretaker Account**

- [ ] 13. On clicking forward button, the modal should always open on the "Visitor's Details" tab while it opens on the tab at which the modal was last closed and there should be a "Next" button in the "Visitor's Details" tab.

- [ ] 14. "Remarks" is marked as required in "Booking Details" tab but the application gets successfully forwarded without filling it.

**From VhIncharge Account**

- [ ] 15. "," in "Rooms".

![2019-09-09 (8)](https://user-images.githubusercontent.com/39924567/64544840-555eef80-d345-11e9-9719-644314b85e5b.png)

**From Student's Account**

- [ ] 16. Unable to cancel a confirmed booking even when form is filled completely.

![2019-09-09 (9)](https://user-images.githubusercontent.com/39924567/64545226-f77ed780-d345-11e9-8627-38d6b36f638e.png)

**Comment by garg3133** [comment]
>  16. Unable to cancel a confirmed booking even when form is filled completely.
> 
> ![2019-09-09 (9)](https://user-images.githubusercontent.com/39924567/64545226-f77ed780-d345-11e9-8627-38d6b36f638e.png)

It only shows this Alert for some reason but the form gets submitted anyways. This alert also appears sometimes while placing a booking request.

**Comment by garg3133** [comment]
**Student's Account**

- [ ] 17. The cancelled bookings are not shown anywhere. There is no need to show the bookings which were cancelled by the user before approval but on cancelling the approved bookings, the bookings after approval of cancellation must be shown somewhere for future reference.

- [ ] 18. Does not shows anywhere whether the application is stuck with VhCaretaker or at the VhIncharge end. There should be three stages of "Status": Pending with VhCaretaker, Pending with VhIncharge and Approved.

**VhCaretaker Account**

- [ ] 19. "Rooms" dropdown in "Booking Details" tab sometimes opens upwards and thus some part of it gets cut.

![2019-09-09 (12)](https://user-images.githubusercontent.com/39924567/64554764-ac6ebf80-d359-11e9-94af-d4ac1c42efb0.png)

**VhIncharge Account**

- [ ] 20.  In "Place a Request" modal, the "Arrival Date" and "Departure Date" date pickers always opens upwards making it impossible to select all dates.

![2019-09-09 (13)](https://user-images.githubusercontent.com/39924567/64555964-1be5ae80-d35c-11e9-83c6-73bc71fd5e88.png)

- [ ] 21. Both "Departure Time" dropdowns sometimes opens upwards and thus do not appear completely.

- [ ] 22. "Category" dropdown sometimes looks like this:

![2019-09-09 (14)](https://user-images.githubusercontent.com/39924567/64556242-a9290300-d35c-11e9-8283-0d6e3df0d074.png)

- [ ] 23. Except "Category" dropdown, no other dropdowns closes when clicked outside of them or on any other field (except for other dropdowns) but closes either on selecting something from dropdown, clicking on the downward arrow or clicking on any other dropdown.
